### ISSUE TITLE
Installation can't seen src (correction: src not added to path)

### ISSUE THREAD

**Issue by LydiaFrance** [alan-turing-institute/python-project-template#49]
The following breaks:

```
my_package
- examples/
-- notebook_walkthrough.ipynb
- src/
-- my_package/ 
--- __init__.py
--- myfunctions.py
```

This fails inside the notebook:
```
from my_package import function
```
> `    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'my_package'",
     "output_type": "error",`

Editing the `setup.cfg` fixes this:

```
[metadata]
name = my_package
version = 0.1.0

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

[options.extras_require]
test =
    pytest >=6
    pytest-cov >=3
    coloredlogs
```

Also hardcoding fixes it: `sys.path.append('../../src/')`

**Comment by phinate** [comment]
Just double-checking this is the right repo to leave this comment? This is a pyproject.toml workflow, and shouldnt contain a setup.cfg.

**Comment by phinate** [comment]
Realising that probably isn't that useful of a comment! The way to fix this problem should just be to include a `pyproject.toml`, which I can't see in your directory tree, which is why I questioned if you generated this project with this template, as that should come batteries-included!

If you do have a `pyproject.toml`, there might have been an installation step missing:

```bash
pip install -e .
```

which is necessary for `src/` layouts, as they will not automatically get picked up by Python when it searches for modules.

Here are a couple of links that I use to remind myself of these things:
- [the PyPA guide on packaging projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
- [Python docs on `src/` vs flat layouts](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)

Hope this helps!

**Comment by phinate** [comment]
I can't reproduce this error with those steps.

My suspicion is that the Python env in your notebook does not match the Python in your terminal. You can test this by running
```python
import sys

print(sys.executable)
```
in your notebook, and see if that matches 
```bash
which python
```
in the terminal.

**Comment by LydiaFrance** [comment]
Okay, after some digging.. the environment was in the right place, python was in the right place, executable path was in the right place, the notebook had the right kernel.... but pip was coming from homebrew. 🤦‍♀️ Thanks!

**Comment by phinate** [comment]
I see! I've gotten a little lazy with this, but one should technically always prefer running `python -m pip ...` in all cases to avoid this :)

**Comment by phinate** [comment]
Nice detective work!
